resolver: lts-6.35

packages:
- ../shared
- .

extra-deps:
- GLURaw-1.5.0.3
- OpenGL-2.12.0.1
- OpenGLRaw-2.5.5.0
- gloss-1.9.4.1
- gloss-algorithms-1.9.4.1
- gloss-rendering-1.9.3.1
- ref-tf-0.4.0.1
- reflex-0.4.0
- reflex-gloss-0.2
